//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.20 at 09:11:38 PM IST 
//


package com.everge.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.everge.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.everge.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TIMECARDLIST }
     * 
     */
    public TIMECARDLIST createTIMECARDLIST() {
        return new TIMECARDLIST();
    }

    /**
     * Create an instance of {@link TIMECARDLIST.TIMECARD }
     * 
     */
    public TIMECARDLIST.TIMECARD createTIMECARDLISTTIMECARD() {
        return new TIMECARDLIST.TIMECARD();
    }

    /**
     * Create an instance of {@link TIMECARDLIST.TIMECARD.TIMEITEMLIST }
     * 
     */
    public TIMECARDLIST.TIMECARD.TIMEITEMLIST createTIMECARDLISTTIMECARDTIMEITEMLIST() {
        return new TIMECARDLIST.TIMECARD.TIMEITEMLIST();
    }

    /**
     * Create an instance of {@link TIMECARDLIST.TIMECARD.TIMEITEMLIST.TIMEITEM }
     * 
     */
    public TIMECARDLIST.TIMECARD.TIMEITEMLIST.TIMEITEM createTIMECARDLISTTIMECARDTIMEITEMLISTTIMEITEM() {
        return new TIMECARDLIST.TIMECARD.TIMEITEMLIST.TIMEITEM();
    }

    /**
     * Create an instance of {@link TIMECARDLIST.TIMECARD.TIMEITEMLIST.TIMEITEM.PROPERTIESLIST }
     * 
     */
    public TIMECARDLIST.TIMECARD.TIMEITEMLIST.TIMEITEM.PROPERTIESLIST createTIMECARDLISTTIMECARDTIMEITEMLISTTIMEITEMPROPERTIESLIST() {
        return new TIMECARDLIST.TIMECARD.TIMEITEMLIST.TIMEITEM.PROPERTIESLIST();
    }

    /**
     * Create an instance of {@link TIMECARDLIST.TIMECARD.TIMEITEMLIST.TIMEITEM.PROPERTIESLIST.PROPERTYITEM }
     * 
     */
    public TIMECARDLIST.TIMECARD.TIMEITEMLIST.TIMEITEM.PROPERTIESLIST.PROPERTYITEM createTIMECARDLISTTIMECARDTIMEITEMLISTTIMEITEMPROPERTIESLISTPROPERTYITEM() {
        return new TIMECARDLIST.TIMECARD.TIMEITEMLIST.TIMEITEM.PROPERTIESLIST.PROPERTYITEM();
    }

}
