//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.20 at 09:11:38 PM IST 
//


package com.everge.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="TIME_CARD" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="ACTION" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="TIME_CARD_ID" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                   &lt;element name="HR_TERM_ID" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                   &lt;element name="HR_ASSIGNMENT_ID" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                   &lt;element name="TIME_CARD_START" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="TIME_CARD_END" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="TIME_ITEM_LIST"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="TIME_ITEM" maxOccurs="unbounded"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="TIME_TYPE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="TIME_UNIT" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                                       &lt;element name="TIME_UOM" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="TIME_ITEM_START" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="TIME_ITEM_END" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="PROPERTIES_LIST"&gt;
 *                                         &lt;complexType&gt;
 *                                           &lt;complexContent&gt;
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                               &lt;sequence&gt;
 *                                                 &lt;element name="PROPERTY_ITEM" maxOccurs="unbounded"&gt;
 *                                                   &lt;complexType&gt;
 *                                                     &lt;complexContent&gt;
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                                         &lt;sequence&gt;
 *                                                           &lt;element name="NAME" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                                           &lt;element name="VALUE" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                                                         &lt;/sequence&gt;
 *                                                       &lt;/restriction&gt;
 *                                                     &lt;/complexContent&gt;
 *                                                   &lt;/complexType&gt;
 *                                                 &lt;/element&gt;
 *                                               &lt;/sequence&gt;
 *                                             &lt;/restriction&gt;
 *                                           &lt;/complexContent&gt;
 *                                         &lt;/complexType&gt;
 *                                       &lt;/element&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "timecard"
})
@XmlRootElement(name = "TIME_CARD_LIST")
public class TIMECARDLIST {

    @XmlElement(name = "TIME_CARD", required = true)
    protected List<TIMECARDLIST.TIMECARD> timecard;

    /**
     * Gets the value of the timecard property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the timecard property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTIMECARD().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TIMECARDLIST.TIMECARD }
     * 
     * 
     */
    public List<TIMECARDLIST.TIMECARD> getTIMECARD() {
        if (timecard == null) {
            timecard = new ArrayList<TIMECARDLIST.TIMECARD>();
        }
        return this.timecard;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="ACTION" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="TIME_CARD_ID" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *         &lt;element name="HR_TERM_ID" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *         &lt;element name="HR_ASSIGNMENT_ID" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *         &lt;element name="TIME_CARD_START" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="TIME_CARD_END" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="TIME_ITEM_LIST"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="TIME_ITEM" maxOccurs="unbounded"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="TIME_TYPE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                             &lt;element name="TIME_UNIT" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *                             &lt;element name="TIME_UOM" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                             &lt;element name="TIME_ITEM_START" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                             &lt;element name="TIME_ITEM_END" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                             &lt;element name="PROPERTIES_LIST"&gt;
     *                               &lt;complexType&gt;
     *                                 &lt;complexContent&gt;
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                                     &lt;sequence&gt;
     *                                       &lt;element name="PROPERTY_ITEM" maxOccurs="unbounded"&gt;
     *                                         &lt;complexType&gt;
     *                                           &lt;complexContent&gt;
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                                               &lt;sequence&gt;
     *                                                 &lt;element name="NAME" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                                                 &lt;element name="VALUE" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *                                               &lt;/sequence&gt;
     *                                             &lt;/restriction&gt;
     *                                           &lt;/complexContent&gt;
     *                                         &lt;/complexType&gt;
     *                                       &lt;/element&gt;
     *                                     &lt;/sequence&gt;
     *                                   &lt;/restriction&gt;
     *                                 &lt;/complexContent&gt;
     *                               &lt;/complexType&gt;
     *                             &lt;/element&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "action",
        "timecardid",
        "hrtermid",
        "hrassignmentid",
        "timecardstart",
        "timecardend",
        "timeitemlist"
    })
    public static class TIMECARD {

        @XmlElement(name = "ACTION", required = true)
        protected String action;
        @XmlElement(name = "TIME_CARD_ID")
        protected int timecardid;
        @XmlElement(name = "HR_TERM_ID")
        protected int hrtermid;
        @XmlElement(name = "HR_ASSIGNMENT_ID")
        protected int hrassignmentid;
        @XmlElement(name = "TIME_CARD_START", required = true)
        protected String timecardstart;
        @XmlElement(name = "TIME_CARD_END", required = true)
        protected String timecardend;
        @XmlElement(name = "TIME_ITEM_LIST", required = true)
        protected TIMECARDLIST.TIMECARD.TIMEITEMLIST timeitemlist;

        /**
         * Gets the value of the action property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getACTION() {
            return action;
        }

        /**
         * Sets the value of the action property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setACTION(String value) {
            this.action = value;
        }

        /**
         * Gets the value of the timecardid property.
         * 
         */
        public int getTIMECARDID() {
            return timecardid;
        }

        /**
         * Sets the value of the timecardid property.
         * 
         */
        public void setTIMECARDID(int value) {
            this.timecardid = value;
        }

        /**
         * Gets the value of the hrtermid property.
         * 
         */
        public int getHRTERMID() {
            return hrtermid;
        }

        /**
         * Sets the value of the hrtermid property.
         * 
         */
        public void setHRTERMID(int value) {
            this.hrtermid = value;
        }

        /**
         * Gets the value of the hrassignmentid property.
         * 
         */
        public int getHRASSIGNMENTID() {
            return hrassignmentid;
        }

        /**
         * Sets the value of the hrassignmentid property.
         * 
         */
        public void setHRASSIGNMENTID(int value) {
            this.hrassignmentid = value;
        }

        /**
         * Gets the value of the timecardstart property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTIMECARDSTART() {
            return timecardstart;
        }

        /**
         * Sets the value of the timecardstart property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTIMECARDSTART(String value) {
            this.timecardstart = value;
        }

        /**
         * Gets the value of the timecardend property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTIMECARDEND() {
            return timecardend;
        }

        /**
         * Sets the value of the timecardend property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTIMECARDEND(String value) {
            this.timecardend = value;
        }

        /**
         * Gets the value of the timeitemlist property.
         * 
         * @return
         *     possible object is
         *     {@link TIMECARDLIST.TIMECARD.TIMEITEMLIST }
         *     
         */
        public TIMECARDLIST.TIMECARD.TIMEITEMLIST getTIMEITEMLIST() {
            return timeitemlist;
        }

        /**
         * Sets the value of the timeitemlist property.
         * 
         * @param value
         *     allowed object is
         *     {@link TIMECARDLIST.TIMECARD.TIMEITEMLIST }
         *     
         */
        public void setTIMEITEMLIST(TIMECARDLIST.TIMECARD.TIMEITEMLIST value) {
            this.timeitemlist = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="TIME_ITEM" maxOccurs="unbounded"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="TIME_TYPE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                   &lt;element name="TIME_UNIT" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
         *                   &lt;element name="TIME_UOM" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                   &lt;element name="TIME_ITEM_START" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                   &lt;element name="TIME_ITEM_END" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                   &lt;element name="PROPERTIES_LIST"&gt;
         *                     &lt;complexType&gt;
         *                       &lt;complexContent&gt;
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                           &lt;sequence&gt;
         *                             &lt;element name="PROPERTY_ITEM" maxOccurs="unbounded"&gt;
         *                               &lt;complexType&gt;
         *                                 &lt;complexContent&gt;
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                                     &lt;sequence&gt;
         *                                       &lt;element name="NAME" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                                       &lt;element name="VALUE" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
         *                                     &lt;/sequence&gt;
         *                                   &lt;/restriction&gt;
         *                                 &lt;/complexContent&gt;
         *                               &lt;/complexType&gt;
         *                             &lt;/element&gt;
         *                           &lt;/sequence&gt;
         *                         &lt;/restriction&gt;
         *                       &lt;/complexContent&gt;
         *                     &lt;/complexType&gt;
         *                   &lt;/element&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "timeitem"
        })
        public static class TIMEITEMLIST {

            @XmlElement(name = "TIME_ITEM", required = true)
            protected List<TIMECARDLIST.TIMECARD.TIMEITEMLIST.TIMEITEM> timeitem;

            /**
             * Gets the value of the timeitem property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the timeitem property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getTIMEITEM().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link TIMECARDLIST.TIMECARD.TIMEITEMLIST.TIMEITEM }
             * 
             * 
             */
            public List<TIMECARDLIST.TIMECARD.TIMEITEMLIST.TIMEITEM> getTIMEITEM() {
                if (timeitem == null) {
                    timeitem = new ArrayList<TIMECARDLIST.TIMECARD.TIMEITEMLIST.TIMEITEM>();
                }
                return this.timeitem;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="TIME_TYPE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *         &lt;element name="TIME_UNIT" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
             *         &lt;element name="TIME_UOM" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *         &lt;element name="TIME_ITEM_START" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *         &lt;element name="TIME_ITEM_END" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *         &lt;element name="PROPERTIES_LIST"&gt;
             *           &lt;complexType&gt;
             *             &lt;complexContent&gt;
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *                 &lt;sequence&gt;
             *                   &lt;element name="PROPERTY_ITEM" maxOccurs="unbounded"&gt;
             *                     &lt;complexType&gt;
             *                       &lt;complexContent&gt;
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *                           &lt;sequence&gt;
             *                             &lt;element name="NAME" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *                             &lt;element name="VALUE" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
             *                           &lt;/sequence&gt;
             *                         &lt;/restriction&gt;
             *                       &lt;/complexContent&gt;
             *                     &lt;/complexType&gt;
             *                   &lt;/element&gt;
             *                 &lt;/sequence&gt;
             *               &lt;/restriction&gt;
             *             &lt;/complexContent&gt;
             *           &lt;/complexType&gt;
             *         &lt;/element&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "timetype",
                "timeunit",
                "timeuom",
                "timeitemstart",
                "timeitemend",
                "propertieslist"
            })
            public static class TIMEITEM {

                @XmlElement(name = "TIME_TYPE", required = true)
                protected String timetype;
                @XmlElement(name = "TIME_UNIT")
                protected int timeunit;
                @XmlElement(name = "TIME_UOM", required = true)
                protected String timeuom;
                @XmlElement(name = "TIME_ITEM_START", required = true)
                protected String timeitemstart;
                @XmlElement(name = "TIME_ITEM_END", required = true)
                protected String timeitemend;
                @XmlElement(name = "PROPERTIES_LIST", required = true)
                protected TIMECARDLIST.TIMECARD.TIMEITEMLIST.TIMEITEM.PROPERTIESLIST propertieslist;

                /**
                 * Gets the value of the timetype property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTIMETYPE() {
                    return timetype;
                }

                /**
                 * Sets the value of the timetype property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTIMETYPE(String value) {
                    this.timetype = value;
                }

                /**
                 * Gets the value of the timeunit property.
                 * 
                 */
                public int getTIMEUNIT() {
                    return timeunit;
                }

                /**
                 * Sets the value of the timeunit property.
                 * 
                 */
                public void setTIMEUNIT(int value) {
                    this.timeunit = value;
                }

                /**
                 * Gets the value of the timeuom property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTIMEUOM() {
                    return timeuom;
                }

                /**
                 * Sets the value of the timeuom property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTIMEUOM(String value) {
                    this.timeuom = value;
                }

                /**
                 * Gets the value of the timeitemstart property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTIMEITEMSTART() {
                    return timeitemstart;
                }

                /**
                 * Sets the value of the timeitemstart property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTIMEITEMSTART(String value) {
                    this.timeitemstart = value;
                }

                /**
                 * Gets the value of the timeitemend property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTIMEITEMEND() {
                    return timeitemend;
                }

                /**
                 * Sets the value of the timeitemend property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTIMEITEMEND(String value) {
                    this.timeitemend = value;
                }

                /**
                 * Gets the value of the propertieslist property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link TIMECARDLIST.TIMECARD.TIMEITEMLIST.TIMEITEM.PROPERTIESLIST }
                 *     
                 */
                public TIMECARDLIST.TIMECARD.TIMEITEMLIST.TIMEITEM.PROPERTIESLIST getPROPERTIESLIST() {
                    return propertieslist;
                }

                /**
                 * Sets the value of the propertieslist property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link TIMECARDLIST.TIMECARD.TIMEITEMLIST.TIMEITEM.PROPERTIESLIST }
                 *     
                 */
                public void setPROPERTIESLIST(TIMECARDLIST.TIMECARD.TIMEITEMLIST.TIMEITEM.PROPERTIESLIST value) {
                    this.propertieslist = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType&gt;
                 *   &lt;complexContent&gt;
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                 *       &lt;sequence&gt;
                 *         &lt;element name="PROPERTY_ITEM" maxOccurs="unbounded"&gt;
                 *           &lt;complexType&gt;
                 *             &lt;complexContent&gt;
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                 *                 &lt;sequence&gt;
                 *                   &lt;element name="NAME" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                 *                   &lt;element name="VALUE" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
                 *                 &lt;/sequence&gt;
                 *               &lt;/restriction&gt;
                 *             &lt;/complexContent&gt;
                 *           &lt;/complexType&gt;
                 *         &lt;/element&gt;
                 *       &lt;/sequence&gt;
                 *     &lt;/restriction&gt;
                 *   &lt;/complexContent&gt;
                 * &lt;/complexType&gt;
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "propertyitem"
                })
                public static class PROPERTIESLIST {

                    @XmlElement(name = "PROPERTY_ITEM", required = true)
                    protected List<TIMECARDLIST.TIMECARD.TIMEITEMLIST.TIMEITEM.PROPERTIESLIST.PROPERTYITEM> propertyitem;

                    /**
                     * Gets the value of the propertyitem property.
                     * 
                     * <p>
                     * This accessor method returns a reference to the live list,
                     * not a snapshot. Therefore any modification you make to the
                     * returned list will be present inside the JAXB object.
                     * This is why there is not a <CODE>set</CODE> method for the propertyitem property.
                     * 
                     * <p>
                     * For example, to add a new item, do as follows:
                     * <pre>
                     *    getPROPERTYITEM().add(newItem);
                     * </pre>
                     * 
                     * 
                     * <p>
                     * Objects of the following type(s) are allowed in the list
                     * {@link TIMECARDLIST.TIMECARD.TIMEITEMLIST.TIMEITEM.PROPERTIESLIST.PROPERTYITEM }
                     * 
                     * 
                     */
                    public List<TIMECARDLIST.TIMECARD.TIMEITEMLIST.TIMEITEM.PROPERTIESLIST.PROPERTYITEM> getPROPERTYITEM() {
                        if (propertyitem == null) {
                            propertyitem = new ArrayList<TIMECARDLIST.TIMECARD.TIMEITEMLIST.TIMEITEM.PROPERTIESLIST.PROPERTYITEM>();
                        }
                        return this.propertyitem;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType&gt;
                     *   &lt;complexContent&gt;
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                     *       &lt;sequence&gt;
                     *         &lt;element name="NAME" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                     *         &lt;element name="VALUE" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
                     *       &lt;/sequence&gt;
                     *     &lt;/restriction&gt;
                     *   &lt;/complexContent&gt;
                     * &lt;/complexType&gt;
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "name",
                        "value"
                    })
                    public static class PROPERTYITEM {

                        @XmlElement(name = "NAME", required = true)
                        protected String name;
                        @XmlElement(name = "VALUE")
                        protected int value;

                        /**
                         * Gets the value of the name property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getNAME() {
                            return name;
                        }

                        /**
                         * Sets the value of the name property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setNAME(String value) {
                            this.name = value;
                        }

                        /**
                         * Gets the value of the value property.
                         * 
                         */
                        public int getVALUE() {
                            return value;
                        }

                        /**
                         * Sets the value of the value property.
                         * 
                         */
                        public void setVALUE(int value) {
                            this.value = value;
                        }

                    }

                }

            }

        }

    }

}
